apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-state-metrics
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-kube-state-strip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /kube-state
            pathType: Prefix
            backend:
              service:
                name: kube-state-metrics
                port:
                  number: 8080
