global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: node-exporter
    metrics_path: /node-exporter/metrics
    static_configs:
      - targets:
          - host.docker.internal:80
        labels:
          app: node-exporter
          env: local

  - job_name: kube-state-metrics
    metrics_path: /kube-state/metrics
    static_configs:
      - targets:
          - host.docker.internal:80
        labels:
          app: kube-state-metrics
          env: local

  - job_name: hello-world
    metrics_path: /hello-world/metrics
    static_configs:
      - targets:
          - host.docker.internal:80
        labels:
          app: hello-world
          env: local
