scrape_configs:
  - job_name: "kube-state-metrics"
    static_configs:
      - targets:
          - "host.docker.internal:38080"

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "host.docker.internal:39100"
